#!/usr/bin/env python3
"""Render Table S5 from five registered LOC-01 rows; do not recalculate statistics."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
from decimal import Decimal
from pathlib import Path


STEM = "Supplementary_Table_S5_per_ring_contact_geometry"
RELEASE = Path(__file__).resolve().parents[3]
TABLES = RELEASE / "02_postprocessing/results/tables"
SOURCE_SHA256 = "5496bd5dab8501b205be7de16eda7ac80fcb6c8e58d4abc96879776bb2f6ba89"
CSV_SHA256 = "af6ff5434e2366a50d01b665a084c3e23aa8f1b0ff020fae2195fcf79cc76523"
METRICS = (
    ("F210_aromatic_proximity_d0p55_per_ring", "TfCut1 F210", "Aromatic-ring proximity"),
    ("F210_any_pi_d0p55_a30_o0p20_per_ring", "TfCut1 F210", "Pi-like geometry"),
    ("L138_nonpolar_d0p40_per_ring", "HiC L138", "Nonpolar contact, 0.40 nm"),
    ("L138_nonpolar_d0p45_per_ring", "HiC L138", r"Nonpolar contact, 0.45 nm$^{\dagger}$"),
    ("L138_nonpolar_d0p50_per_ring", "HiC L138", r"Nonpolar contact, 0.50 nm$^{\dagger}$"),
)

PREAMBLE = r"""% Generated by tables/build_supplementary_table_s5.py from the local LOC-01 CSV.
\begin{table}[H]
  \caption{PET-ring-normalized local-geometry fractions for TfCut1 F210 and HiC L138.}
  \label{tab:per_ring_contact_geometry}
  \centering
  \small
  \setlength{\tabcolsep}{4pt}
  \renewcommand{\tabularxcolumn}[1]{m{#1}}
  \begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}m{1.5cm}>{\raggedright\arraybackslash}Xccccc@{}}
    \toprule
    Target & Per-ring metric & $n_{10}/n_{20}$ & \shortstack{Mean\\L10} &
    \shortstack{Mean\\L20} & $\Delta$ & \shortstack{95\% interval\\for $\Delta$} \\
    \midrule
"""

POSTAMBLE = r"""    \bottomrule
  \end{tabularx}

  \vspace{4pt}
  \parbox{\linewidth}{\footnotesize
  For each analyzed frame, the number of PET aromatic rings meeting the stated
  criterion was divided by the total number of PET aromatic rings (10 for L10
  and 20 for L20). These framewise fractions were averaged over 20--100 ns
  within each retained trajectory, and the trajectory means were averaged
  within each enzyme--length group, including zero values. $n_{10}$ and
  $n_{20}$ denote retained-trajectory counts, and $\Delta$ is the L20-minus-L10
  difference in group means. The 95\% intervals are percentile intervals from
  20,000 bootstrap resamples of whole trajectories performed separately within
  the L10 and L20 groups. Aromatic-ring proximity requires a protein--PET
  ring-centroid distance below 0.55 nm. Pi-like geometry additionally requires
  a projected ring-center offset below 0.20 nm and ring planes within
  $30\si{\degree}$ of parallel or perpendicular. The projected offset is the
  smaller projection of the centroid-to-centroid vector onto the two ring
  planes. Nonpolar contacts use the minimum distance between L138 side-chain
  carbon atoms and PET aromatic-ring carbon atoms. The 0.40-nm cutoff is
  primary, and daggers mark the 0.45- and 0.50-nm sensitivity cutoffs.
  The candidates were selected after the residue-contact screen, and the
  intervals are descriptive and unadjusted for multiple comparisons.
  Values are rounded to four decimal places from the full-precision source data.}
\end{table}
"""


def verify_hash(data: bytes, expected: str, description: str) -> None:
    actual = hashlib.sha256(data).hexdigest()
    if actual != expected:
        raise ValueError(f"{description} SHA-256 mismatch: {actual}")


def project_source(source: Path) -> bytes:
    data = source.read_bytes()
    verify_hash(data, SOURCE_SHA256, "Registered LOC-01 source")
    reader = csv.DictReader(io.StringIO(data.decode("utf-8")))
    rows = list(reader)
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=reader.fieldnames, lineterminator="\n")
    writer.writeheader()
    for metric_id, _, _ in METRICS:
        selected = [row for row in rows if row["metric_id"] == metric_id]
        if len(selected) != 1:
            raise ValueError(f"Expected exactly one source row for {metric_id}")
        writer.writerow(selected[0])
    result = output.getvalue().encode("utf-8")
    verify_hash(result, CSV_SHA256, "Five-row projection")
    return result


def render(data: bytes) -> str:
    verify_hash(data, CSV_SHA256, "Local Table S5 CSV")
    reader = csv.DictReader(io.StringIO(data.decode("utf-8")))
    rows = list(reader)
    if len(reader.fieldnames or []) != 26 or len(rows) != 5:
        raise ValueError("Expected five rows and all 26 original source fields")
    lines = []
    for row, (metric_id, target, label) in zip(rows, METRICS, strict=True):
        expected_n = ("6", "6") if target.startswith("TfCut1") else ("5", "8")
        if (row["metric_id"] != metric_id or row["scope"] != "per_pet_ring"
                or (row["n_l10"], row["n_l20"]) != expected_n):
            raise ValueError(f"Metric or population mismatch: {metric_id}")
        lo, hi = (Decimal(row[key]) for key in ("delta_ci95_low", "delta_ci95_high"))
        if not lo < 0 < hi or row["ci_excludes_zero"] != "False":
            raise ValueError(f"Interval classification mismatch: {metric_id}")
        means = [Decimal(row[key]) for key in ("mean_l10", "mean_l20")]
        delta = Decimal(row["delta_l20_minus_l10"])
        if not all(0 <= mean <= 1 for mean in means) or abs(means[1] - means[0] - delta) > Decimal("1e-15"):
            raise ValueError(f"Mean/difference consistency failure: {metric_id}")
        # Round each source value independently, never subtract rounded means.
        cells = [target, label, "/".join(expected_n), *(f"{v:.4f}" for v in means),
                 f"${delta:+.4f}$", f"$[{lo:+.4f}, {hi:+.4f}]$"]
        lines.append("    " + " & ".join(cells) + r" \\" + "\n")
    return PREAMBLE + "".join(lines) + POSTAMBLE


def verify_or_create(path: Path, data: bytes, check: bool) -> None:
    if path.exists():
        if path.read_bytes() != data:
            raise ValueError(f"Existing output differs; refusing to overwrite {path}")
    elif check:
        raise ValueError(f"Missing output: {path}")
    else:
        with path.open("xb") as handle:
            handle.write(data)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, help="Optional original LOC-01 CSV, verified by its registered hash")
    parser.add_argument("--check", action="store_true", help="Read-only verification of CSV and generated TeX")
    parser.add_argument("--stdout", action="store_true", help="Print generated TeX without writing files")
    parser.add_argument("--output", type=Path, help="Write generated TeX to a new file outside the package")
    args = parser.parse_args()
    if args.check and args.stdout:
        parser.error("Choose --check or --stdout")
    if args.output and (args.check or args.stdout):
        parser.error("Choose --output, --check or --stdout")
    csv_path = TABLES / f"{STEM}.csv"
    data = project_source(args.source) if args.source else csv_path.read_bytes()
    tex = render(data).encode("utf-8")
    if args.output:
        output=args.output.resolve()
        if output==RELEASE or RELEASE in output.parents or output.exists():
            parser.error("Use a new output file outside the package")
        output.parent.mkdir(parents=True,exist_ok=True)
        verify_or_create(output,tex,False)
        print("PASS: generated Table S5 in the requested external output file")
        return
    if args.stdout:
        print(tex.decode("utf-8"), end="")
        return
    verify_or_create(csv_path, data, args.check)
    verify_or_create(TABLES / f"{STEM}.tex", tex, args.check)
    print(f"PASS: Table S5, 5 rows, 26 full-precision fields; CSV SHA-256 {CSV_SHA256}")


if __name__ == "__main__":
    main()
